version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ~/volumes/prometheus/:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
    - 3000:3000
    depends_on:
      - prometheus
