version: "3"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379

